### ISSUE TITLE
Switching to new source unit format

### ISSUE THREAD

**Issue by alexsaveliev** [sourcegraph/srclib-csharp#10]
Please switch to new source unit format introduced in sourcegraph/srclib@c33bfb7bafb8f7795756d71d4dbcae73ada51b3a
- No more `Config` and `Ops`
- Format of `Dependencies` has been changed, now it holds array of 
  - Name?
  - Version?
  - Type?
  - Repo?
  - CommitID?

If you need additional properties of dependencies, you may put them into the `Data` section

**Comment by ildarisaev** [comment]
Modified toolchain accordingly

(but haven't released new docker image yet)
